-- MEMBER 테이블
CREATE TABLE MEMBER(
	MEMBER_NO NUMBER  PRIMARY KEY,
	MEMBER_ID VARCHAR2(30) NOT NULL,
	MEMBER_PASSWORD VARCHAR2(30) NOT NULL,
	PHONE_NUMBER VARCHAR2(20),
	DELETE_YN CHAR(1) DEFAULT 'N' CHECK(DELETE_YN IN('Y','N'))
);

COMMENT ON COLUMN MEMBER.MEMBER_NO  IS '회원번호';
COMMENT ON COLUMN MEMBER.MEMBER_ID  IS '아이디';
COMMENT ON COLUMN MEMBER.MEMBER_PASSWORD  IS '비밀번호';
COMMENT ON COLUMN MEMBER.PHONE_NUMBER  IS '핸드폰번호';
COMMENT ON COLUMN MEMBER.DELETE_YN  IS '삭제여부';

CREATE TABLE BOARD (
	BOARD_NO NUMBER PRIMARY KEY,
	BOARD_TITLE VARCHAR2(300) NOT NULL,
	BOARD_CONTENT VARCHAR2(4000) NOT NULL,
	BOARD_WRITER NUMBER REFERENCES MEMBER(MEMBER_NO),
	CREATE_DATE DATE DEFAULT SYSDATE
);

COMMENT ON COLUMN BOARD.BOARD_NO  IS '글번호';
COMMENT ON COLUMN BOARD.BOARD_TITLE  IS '글제목';
COMMENT ON COLUMN BOARD.BOARD_CONTENT  IS '글내용';
COMMENT ON COLUMN BOARD.BOARD_WRITER  IS '작성자';
COMMENT ON COLUMN BOARD.CREATE_DATE  IS '작성일자';

CREATE SEQUENCE SEQ_MEMBER_NO
START WITH 100
INCREMENT BY 100;

INSERT INTO MEMBER (MEMBER_NO,MEMBER_ID, MEMBER_PASSWORD)
VALUES(SEQ_MEMBER_NO.NEXTVAL, 'step1', 'step11');


INSERT INTO MEMBER (MEMBER_NO,MEMBER_ID, MEMBER_PASSWORD,PHONE_NUMBER)
VALUES(SEQ_MEMBER_NO.NEXTVAL, 'step2', 'step22','010-1111-2222');

INSERT INTO MEMBER (MEMBER_NO,MEMBER_ID, MEMBER_PASSWORD)
VALUES(SEQ_MEMBER_NO.NEXTVAL,'step3', 'step33');

SELECT * FROM MEMBER;

CREATE SEQUENCE SEQ_BOARD_NO
START WITH 1
INCREMENT BY 1;

INSERT INTO BOARD
VALUES(SEQ_BOARD_NO.NEXTVAL, '첫 글', '스텝평가','100','2023-03-12');

INSERT INTO BOARD
VALUES(SEQ_BOARD_NO.NEXTVAL, '두 번째 글', '재밌다','300','2023-03-12');

INSERT INTO BOARD
VALUES(SEQ_BOARD_NO.NEXTVAL, '세 번째 글', '하하하', '200', '2023-03-12');

SELECT BOARD_NO 글번호, BOARD_TITLE 제목, BOARD_CONTENT 내용, MEMBER_ID 작성자, CREATE_DATE
FROM BOARD 
LEFT JOIN MEMBER ON(BOARD_WRITER = MEMBER_NO)
ORDER BY BOARD_NO DESC; 










