-- 시퀀즈 생성
CREATE SEQUENCE SEQ_MEMBER_NO NOCACHE; -- 회원번호
CREATE SEQUENCE SEQ_BOARD_NO NOCACHE; -- 게시글번호
CREATE SEQUENCE SEQ_COMMENT_NO NOCACHE; -- 댓글번호

-- MEMBER 테이블에 INSERT 하기
INSERT INTO MEMBER
VALUES(SEQ_MEMBER_NO.NEXTVAL, 
	'jdb4142@naver.com', 
	'123123',
	'1번회원',
	'01012341234',
	'서울시 중구', 
	DEFAULT, DEFAULT);
	
COMMIT;

SELECT * FROM MEMBER;

-- 로그인 
SELECT MEMBER_NO, MEMBER_NICKNAME , MEMBER_TEL, MEMBER_ADDRESS ,
	TO_CHAR(ENROLL_DATE, 'YYYY"년" MM"월" DD"일" HH24:MI:SS') ENROLL_DATE
FROM MEMBER
WHERE MEMBER_EMAIL = 'mem01@google.com'
AND MEMBER_PW = '123123'
AND MEMBER_DEL_FL = 'N';

-- MEMBER 테이블 전체 조회
SELECT * FROM MEMBER
--ORDER BY MEMBER_NO; -- 오름차순
ORDER BY MEMBER_NO DESC ; -- 내림차순


-- 닉네임 전화번호 수정
UPDATE MEMBER SET 
MEMBER_NICKNAME = '별명',
MEMBER_TEL = '01012366666'
WHERE MEMBER_NO = 5;

-- 회원 정보 수정
UPDATE MEMBER SET 
MEMBER_NICKNAME  = '별명',
MEMBER_TEL = '01012345678',


-- BOARD 테이블에 INSERT 하기
-- (실행 후 COMMIT/ROLLBAKC 무조건 수행)
INSERT INTO BOARD
VALUES(SEQ_BOARD_NO.NEXTVAL,
		'게시글 제목',
		'게시글 내용',
		DEFAULT, DEFAULT,DEFAULT,5);
	
COMMIT;

		
		

SELECT * FROM BOARD;


-- 게시글 번호를 입력 받아 일치하는 게시글의
-- 제목, 내용, 작성일, 조회수, 작성자번호, 작성자 닉네임 조회
-- 단, 삭제되지 않은 게시글만 조회 가능(BOARD_DEL_FL = 'N')
SELECT BOARD_TITLE, BOARD_CONTENT, 
	TO_CHAR(B_CREATE_DATE, 'YYYY-MM-DD HH24:MI:SS') B_CREATE_DATE,
	READ_COUNT, MEMBER_NO, MEMBER_NICKNAME
FROM BOARD 
JOIN MEMBER USING(MEMBER_NO)
WHERE BOARD_DEL_FL = 'N'
AND BOARD_NO = 1;


-- 2) 로그인 상태인 경우 게시글 번호를 입력 받아
-- 해당 게시글 작성 회원 번호(BOARD.MEMBER_NO)와 
-- 로그인한 회원의 회원 번호(MEMBER.MEMBER_NO)가 일치하는지 확인하는 service 메서드 호출

-- 
UPDATE BOARD SET 
BOARD_TITLE = '',
BOARD_CONTENT = ''
WHERE BOARD_NO =  ;





