-- 시퀀즈 생성
CREATE SEQUENCE SEQ_MEMBER_NO NOCACHE; -- 회원번호
CREATE SEQUENCE SEQ_BOARD_NO NOCACHE; -- 게시글번호
CREATE SEQUENCE SEQ_COMMENT_NO NOCACHE; -- 댓글번호

-- MEMBER 테이블에 INSERT 하기
INSERT INTO MEMBER
VALUES(SEQ_MEMBER_NO.NEXTVAL, 
	'jdb4142@naver.com', 
	'123123',
	'1번회원',
	'01012341234',
	'서울시 중구', 
	DEFAULT, DEFAULT);
	
COMMIT;

SELECT * FROM MEMBER;